server:
  port: 7505
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/internspringboot
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create-drop
    show-sql: true
application:
  security:
    jwt:
      base64SecretKey: dHBVcFM1dl5adFV2RXRhZk1xKFt9b2E2RT56d2JuI2I  #${BASE64_SECRET_KEY}
      accessTokenExpirationMillis: 1800000 # 30 phút
      refreshTokenExpirationMillis: 604800000 # 7 ngày